<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('infos')->insert([
            'titulo_principal' => 'Los Mejores Juegos',

            'info_principal' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',

            'info_nosotros' => '<p style="text-align: justify;">Tenemos más de 15 años de experiencia Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean Lorem ipsm dolor sit the power of consectetur adi pisi cing elit, sed do eiusmod tempor xercitationemut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean bibendum nec risus et suscipit Curabitur metus ipsum. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system.</p><p style="text-align: justify;">Paulo offendit cu vix. Ne modo ignota putant mei. Probo theophrastus no per. Dicit graeci an vis. Hinc deseruisse argumentum ea ius, duo amet nibh docendi eu. An pro verear vulputate, mucius semper eu pro, id partem essent nam. Ne idque timeam sea.</p><p style="text-align: justify;">In perpetua maluisset cotidieque mel, usu ei electram similique. Tritani quaestio dissentias has ne. Eloquentiam definitionem has an, ut pro tation essent invenire, at vis quas aliquip. Semper maiestatis pro eu. Ad mei tota prima. Falli audiam erroribus ea has, aperiam praesent ei mel. Ei purto ipsum vel, an doctus fuisset nam, sit in tota impetus. Cu posse sonet utamur vel. Sea no quem cibo tota. Cu vim partem mediocritatem. Et purto veritus abhorreant sed, ex eros zril ridens ius. His ei sale velit disputando. Id eos eros sententiae consequuntur. Cu cum nostrud appareat, torquatos mnesarchum incorrupte eu has. Eos aliquid deleniti consectetuer in.</p><p style="text-align: justify;">&nbsp;Vix vitae legere eu, iudico contentiones et mel, at velit feugait ius.
            
            
            Cetero facilisis ea qui, eos nulla assueverit cu. Nobis minimum ne usu, nam id porro mandamus. Conceptam accommodare id eum. No sea tibique offendit reprimique, mea ex tantas praesent adversarium. In mel habeo animal utamur, cu delenit recteque consequat quo.
            
            Oporteat intellegam cotidieque sit id. Legimus ponderum pro an, ipsum atqui omnium ius ei, mea eu eius ipsum.&nbsp;</p><p style="text-align: justify; ">No iisque adversarium suscipiantur est, modus urbanitas eos at.
            
            Oporteat intellegam cotidieque sit id. Legimus ponderum pro an, ipsum atqui omnium ius ei, mea eu eius ipsum. No iisque adversarium suscipiantur est, modus urbanitas eos at. Perpetua elaboraret interpretaris ea duo, omnis laoreet id pro, mei at facete pericula. Cum velit assum forensibus ne, vix maiorum senserit cu. At mei nonumes inimicus, mea at appetere rationibus.</p><blockquote style="text-align: center;">Vix vitae legere eu, iudico contentiones et mel, at velit feugait ius.</blockquote><p style="text-align: justify;">Veri legimus philosophia nec ne, usu ne ipsum denique sententiae, aliquip qualisque cum no.
            
            omnis laoreet id pro
            
            
            Et elitr urbanitas has. Ea eos nullam mentitum reprehendunt. Cibo soluta definiebas pro in, eius bonorum definitiones mel an. Ea equidem eloquentiam nec, dicat delectus intellegebat an nec, eligendi adipisci scripserit an eos. Ius ne quaeque corpora.</p><h3 style="text-align: center;">Et purto veritus abhorreant sed</h3><p style="text-align: justify;">Perpetua elaboraret interpretaris ea duo, omnis laoreet id pro, mei at facete pericula. Cum velit assum forensibus ne, vix maiorum senserit cu. At mei nonumes inimicus, mea at appetere rationibus.<br></p><p style="text-align: justify; ">Falli audiam erroribus ea has, aperiam praesent ei mel. Ei purto ipsum vel, an doctus fuisset nam, sit in tota impetus. Cu posse sonet utamur vel. Sea no quem cibo tota. Cu vim partem mediocritatem. Et purto veritus abhorreant sed, ex eros zril ridens ius. His ei sale velit disputando. Id eos eros sententiae consequuntur. Cu cum nostrud appareat, torquatos mnesarchum incorrupte eu has. Eos aliquid deleniti consectetuer in.<br></p>',

            'direccion' => 'Torre Xerox, Piso3, Bello Campo, Caracas, Venezuela.',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego A',
            'info' => '<p> Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ</p><p>Lorem ipsum dolor sit amet, reque elitr sit ea, placerat reprimique ea pro? Mei adhuc reque oblique id. Modo summo scripserit nec ad, an enim laoreet volumus sit, choro ignota gloriatur has ex! Eu vix case tacimates qualisque, petentium consulatu quo ex. Id dolore ancillae petentium duo, accusata pertinacia vix et? Ius ex suas timeam, soleat iisque est at, eos percipitur delicatissimi ea.</p><br><p>Ei veri audire mei, vix phaedrum conclusionemque no, eu solum sententiae consetetur mea? Ea docendi partiendo temporibus vix? Sit periculis patrioque voluptatibus et, nam propriae honestatis no, ex sed essent impetus legendos. In vero signiferumque mea, putent salutatus his te? Eum id tale gubergren constituto. Ex cum malorum numquam euismod, accusata forensibus pri ei, delicata accusamus sed no.</p>',
            'UrlImg' => 'juego-1505707510.jpg',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego B',
            'info' => '<p>Lorem ipsum dolor sit amet, reque elitr sit ea, placerat reprimique ea pro? Mei adhuc reque oblique id. Modo summo scripserit nec ad, an enim laoreet volumus sit, choro ignota gloriatur has ex! Eu vix case tacimates qualisque, petentium consulatu quo ex. Id dolore ancillae petentium duo, accusata pertinacia vix et? Ius ex suas timeam, soleat iisque est at, eos percipitur delicatissimi ea.</p><br><p>Ei veri audire mei, vix phaedrum conclusionemque no, eu solum sententiae consetetur mea? Ea docendi partiendo temporibus vix? Sit periculis patrioque voluptatibus et, nam propriae honestatis no, ex sed essent impetus legendos. In vero signiferumque mea, putent salutatus his te? Eum id tale gubergren constituto. Ex cum malorum numquam euismod, accusata forensibus pri ei, delicata accusamus sed no.</p><br><p>Est posse philosophia voluptatibus ei, purto maiestatis liberavisse eos eu? Ius hinc quidam consequat at, vix ad choro senserit. Sea ei praesent moderatius, his tibique placerat an. Has eu soluta menandri gubergren, at maiestatis reprimique his. Nec ea simul sapientem expetendis, ius an elitr omnium? Sed ne verear scripserit.</p><br><p>Choro audiam est ex, saepe menandri et cum, adhuc fugit iudico id eum. Vel ex populo omnium, id nam mundi argumentum, accusamus democritum et vel. Mea prima tractatos qualisque in, vel elitr maiestatis definitiones id. Vis soleat forensibus ut? Amet vocibus ullamcorper ex eos, utinam blandit duo ei?</p><br><p>Assum meliore id eam, id sea viderer volumus, ne vel brute everti. Vix eu sonet latine, id mel modo luptatum. Cu eam repudiare repudiandae! Tritani scripserit et nam, cu pri graeci melius veritus, ius ut iisque dolorum. At vulputate cotidieque vim, incorrupte deterruisset id mel, ne sit luptatum atomorum efficiantur.</p><br><p>Eu tollit sanctus docendi est, quando dolorum liberavisse nam eu! Et ius rebum harum pericula, fierent lucilius in duo, dictas iuvaret eloquentiam eos in? Ex mediocrem expetendis cum, ea aliquid oportere consulatu mei, quod diceret usu in. Et has quot debitis suscipit, per ex meliore perpetua dissentiunt. Magna ubique sed et, labore lobortis qui ex. Ut duo tation voluptatum<br></p>',
            'UrlImg' => 'juego-1505707573.jpg',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego C',
            'info' => '<p>Lorem ipsum dolor sit amet, reque elitr sit ea, placerat reprimique ea pro? Mei adhuc reque oblique id. Modo summo scripserit nec ad, an enim laoreet volumus sit,  Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ Λορεμ ιπσθμ δολορ σιτ αμετ, νοvθμ φαβελλασ πετεντιθμ vελ νε, ατ νισλ σονετ οπορτερε εθμ. Αλιι δοcτθσ μει ιδ, νο αθτεμ αθδιρε ιντερεσσετ μελ, δοcενδι cομμθνε οπορτεατ τε cθμ choro ignota gloriatur has ex! Eu vix case tacimates qualisque, petentium consulatu quo ex. Id dolore ancillae petentium duo, accusata pertinacia vix et? Ius ex suas timeam, soleat iisque est at, eos percipitur delicatissimi ea.</p><br><p>Ei veri audire mei, vix phaedrum conclusionemque no, eu solum sententiae consetetur mea? Ea docendi partiendo temporibus vix? Sit periculis patrioque voluptatibus et, nam propriae honestatis no, ex sed essent impetus legendos. In vero signiferumque mea, putent salutatus his te? Eum id tale gubergren constituto. Ex cum malorum numquam euismod, accusata forensibus pri ei, delicata accusamus sed no.</p>',
            'UrlImg' => 'juego-1505707667.jpg',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego D',
            'info' => 'Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит. Иус цу цибо саперет сцрипсерит,Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит. Иус цу цибо саперет сцрипсерит,Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит. Иус цу цибо саперет сцрипсерит,Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит. Иус цу цибо саперет сцрипсерит,Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит. Иус цу цибо саперет сцрипсерит,Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит. Иус цу цибо саперет сцрипсерит,Лорем ипсум долор сит амет, пер цлита поссит ех, ат мунере фабулас петентиум сит.
            
            Иус цу цибо саперет сцрипсерит,Lorem ipsum dolor sit amet, reque elitr sit ea, placerat reprimique ea pro? Mei adhuc reque oblique id. Modo summo scripserit nec ad, an enim laoreet volumus sit, choro ignota gloriatur has ex! Eu vix case tacimates qualisque, petentium consulatu quo ex. Id dolore ancillae petentium duo, accusata pertinacia vix et? Ius ex suas timeam, soleat iisque est at, eos percipitur delicatissimi ea.
            
            Ei veri audire mei, vix phaedrum conclusionemque no, eu solum sententiae consetetur mea? Ea docendi partiendo temporibus vix? Sit periculis patrioque voluptatibus et, nam propriae honestatis no, ex sed essent impetus legendos. In vero signiferumque mea, putent salutatus his te? Eum id tale gubergren constituto. Ex cum malorum numquam euismod, accusata forensibus pri ei, delicata accusamus sed no.
            
            Est posse philosophia voluptatibus ei, purto maiestatis liberavisse eos eu? Ius hinc quidam consequat at, vix ad choro senserit. Sea ei praesent moderatius, his tibique placerat an. Has eu soluta menandri gubergren, at maiestatis reprimique his. Nec ea simul sapientem expetendis, ius an elitr omnium? Sed ne verear scripserit.',
            'UrlImg' => 'juego-1505707713.jpg',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego E',
            'info' => 'पढाए हिंदी रहारुप अनुवाद कार्यलय मुख्य संस्था सोफ़तवेर निरपेक्ष उनका आपके बाटते आशाआपस मुख्यतह उशकी करता। शुरुआत संस्था कुशलता मेंभटृ अनुवाद गएआप विशेष सकते परिभाषित लाभान्वित प्रति देकर समजते दिशामे प्राप्त जैसे वर्णन संस्थान निर्माता प्रव्रुति भाति चुनने उपलब्ध बेंगलूर अर्थपुर्णपढाए हिंदी रहारुप अनुवाद कार्यलय मुख्य संस्था सोफ़तवेर निरपेक्ष उनका आपके बाटते आशाआपस मुख्यतह उशकी करता। शुरुआत संस्था कुशलता मेंभटृ अनुवाद गएआप विशेष सकते परिभाषित लाभान्वित प्रति देकर समजते दिशामे प्राप्त जैसे वर्णन संस्थान निर्माता प्रव्रुति भाति चुनने उपलब्ध बेंगलूर अर्थपुर्णपढाए हिंदी रहारुप अनुवाद कार्यलय मुख्य संस्था सोफ़तवेर निरपेक्ष उनका आपके बाटते आशाआपस मुख्यतह उशकी करता। शुरुआत संस्था कुशलता मेंभटृ अनुवाद गएआप विशेष सकते परिभाषित लाभान्वित प्रति देकर समजते दिशामे प्राप्त जैसे वर्णन संस्थान निर्माता प्रव्रुति भाति चुनने उपलब्ध बेंगलूर अर्थपुर्णपढाए हिंदी रहारुप अनुवाद कार्यलय मुख्य संस्था सोफ़तवेर निरपेक्ष उनका आपके बाटते आशाआपस मुख्यतह उशकी करता। शुरुआत संस्था कुशलता मेंभटृ अनुवाद गएआप विशेष सकते परिभाषित लाभान्वित प्रति देकर समजते दिशामे प्राप्त जैसे वर्णन संस्थान निर्माता प्रव्रुति भाति चुनने उपलब्ध बेंगलूर अर्थपुर्णLorem ipsum dolor sit amet, reque elitr sit ea, placerat reprimique ea pro? Mei adhuc reque oblique id. Modo summo scripserit nec ad, an enim laoreet volumus sit, choro ignota gloriatur has ex! Eu vix case tacimates qualisque, petentium consulatu quo ex. Id dolore ancillae petentium duo, accusata pertinacia vix et? Ius ex suas timeam, soleat iisque est at, eos percipitur delicatissimi ea.
            
            Ei veri audire mei, vix phaedrum conclusionemque no, eu solum sententiae consetetur mea? Ea docendi partiendo temporibus vix? Sit periculis patrioque voluptatibus et, nam propriae honestatis no, ex sed essent impetus legendos. In vero signiferumque mea, putent salutatus his te? Eum id tale gubergren constituto. Ex cum malorum numquam euismod, accusata forensibus pri ei, delicata accusamus sed no.',
            'UrlImg' => 'juego-1505707781.jpg',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego F',
            'info' => '<p>Lorem ipsum dolor sit amet, reque elitr sit ea, placerat reprimique ea pro? Mei adhuc reque oblique id. Modo summo scripserit nec ad, an enim laoreet volumus sit, choro ignota gloriatur has ex! Eu vix case tacimates qualisque, petentium consulatu quo ex. Id dolore ancillae petentium duo, accusata pertinacia vix et? Ius ex suas timeam, soleat iisque est at, eos percipitur delicatissimi ea.</p><br><p>Ei veri audire mei, vix phaedrum conclusionemque no, eu solum sententiae consetetur mea? Ea docendi partiendo temporibus vix? Sit periculis patrioque voluptatibus et, nam propriae honestatis no, ex sed essent impetus legendos. In vero signiferumque mea, putent salutatus his te? Eum id tale gubergren constituto. Ex cum malorum numquam euismod, accusata forensibus pri ei, delicata accusamus sed no.</p><br><p>Est posse philosophia voluptatibus ei, purto maiestatis liberavisse eos eu? Ius hinc quidam consequat at, vix ad choro senserit. Sea ei praesent moderatius, his tibique placerat an. Has eu soluta menandri gubergren, at maiestatis reprimique his. Nec ea simul sapientem expetendis, ius an elitr omnium? Sed ne verear scripserit.</p><br><p><br></p>',
            'UrlImg' => 'juego-1505707818.jpg',
        ]);
        DB::table('juegos')->insert([
            'titulo' => 'Juego G',
            'info' => '<p>旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。旅ロ京青利セムレ弱改フヨス波府かばぼ意送でぼ調掲察たス日西重ケアナ住橋ユムミク順待ふかんぼ人奨貯鏡すびそ。<br></p>',
            'UrlImg' => 'juego-1505707836.jpg',
        ]);
    }
}
